"""Train a frozen-Point query-failure head on Fashion-IQ-C labels.

The Point backbone is intentionally frozen in the reliability probe. This preserves
the validated retrieval function and makes the failure label (generated by that
same checkpoint) stationary.  Retrieval loss is monitored in the documented
total objective; only the failure term updates the new head.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import sys
from pathlib import Path

import numpy as np
import torch
from PIL import Image
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm

ROOT = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from data import get_transform
EVAL_DIR = ROOT / "eval"
if str(EVAL_DIR) not in sys.path:
    sys.path.insert(0, str(EVAL_DIR))
from robustness_legacy import get_tokenizer_and_processor
from models.reliability_model import ReliabilityAwareCIR
from modules.fiqc import FIQC_SCHEMA_VERSION, FIQCCorruptionGenerator
from modules.losses import HUGLoss
from modules.reliability import failure_prediction_loss, reliability_metrics
from utils.artifact_paths import resolve_artifact_path


def load_manifest(path):
    with open(path, encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]


class ReliabilityTrainingDataset(Dataset):
    def __init__(self, rows, data_root, processor, tokenizer, transform):
        self.rows, self.image_dir = rows, Path(data_root) / "images"
        self.processor, self.tokenizer, self.transform = processor, tokenizer, transform

    def __len__(self):
        return len(self.rows)

    def __getitem__(self, index):
        row = self.rows[index]
        reference = Image.open(self.image_dir / f"{row['candidate_id']}.png").convert("RGB")
        target = Image.open(self.image_dir / f"{row['target_id']}.png").convert("RGB")
        if row["modality"] == "image" and row["severity"] > 0:
            reference, _ = FIQCCorruptionGenerator(row["corruption_seed"]).image(
                reference, row["corruption_type"], row["severity"], row["query_index"],
            )
        processed = self.processor(row["corrupted_text"])
        tokens = self.tokenizer(
            processed, return_tensors="pt", padding="max_length", truncation=True, max_length=77,
        )
        return {
            "ref_image": self.transform(reference), "target_image": self.transform(target),
            "text_input_ids": tokens["input_ids"].squeeze(0),
            "text_attention_mask": tokens["attention_mask"].squeeze(0),
            "failure_label": float(row["failure_label"]), "row": row,
        }


def collate(batch):
    return {
        "ref_images": torch.stack([item["ref_image"] for item in batch]),
        "target_images": torch.stack([item["target_image"] for item in batch]),
        "text_input_ids": torch.stack([item["text_input_ids"] for item in batch]),
        "text_attention_mask": torch.stack([item["text_attention_mask"] for item in batch]),
        "failure_labels": torch.tensor([item["failure_label"] for item in batch]),
        "rows": [item["row"] for item in batch],
    }


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data_root", required=True); parser.add_argument("--point_checkpoint", required=True)
    parser.add_argument("--train_manifest", required=True); parser.add_argument("--val_manifest", required=True)
    parser.add_argument("--output_dir", required=True); parser.add_argument("--resume_checkpoint")
    parser.add_argument("--batch_size", type=int, default=32); parser.add_argument("--num_workers", type=int, default=4)
    parser.add_argument("--num_epochs", type=int, default=10); parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--weight_decay", type=float, default=1e-4)
    parser.add_argument("--lambda_failure", type=float, default=1.0)
    parser.add_argument("--bottleneck_dim", type=int, default=256); parser.add_argument("--dropout", type=float, default=0.1)
    parser.add_argument("--ece_bins", type=int, default=10); parser.add_argument("--patience", type=int, default=3)
    parser.add_argument("--max_train_rows", type=int); parser.add_argument("--max_val_rows", type=int)
    parser.add_argument("--seed", type=int, default=42); parser.add_argument("--tqdm_mininterval", type=float, default=1.0)
    return parser.parse_args()


def set_seed(seed):
    random.seed(seed); np.random.seed(seed); torch.manual_seed(seed); torch.cuda.manual_seed_all(seed)


def validate_manifests(train_rows, val_rows, point_checkpoint):
    required = {
        "schema_version", "query_id", "split", "category", "candidate_id", "target_id", "corrupted_text",
        "modality", "corruption_type", "severity", "corruption_seed", "failure_k", "failure_label",
        "label_checkpoint",
    }
    for name, rows in (("train", train_rows), ("val", val_rows)):
        if not rows:
            raise ValueError(f"{name} manifest is empty")
        missing = required - set(rows[0])
        if missing:
            raise ValueError(f"{name} manifest missing fields: {sorted(missing)}")
        if {row["split"] for row in rows} != {name}:
            raise ValueError(f"{name} manifest must contain only split={name}")
        schemas = {row["schema_version"] for row in rows}
        if schemas != {FIQC_SCHEMA_VERSION}:
            raise ValueError(f"{name} manifest must use Fashion-IQ-C schema v{FIQC_SCHEMA_VERSION}")
        if len({row["category"] for row in rows}) != 1 or len({row["failure_k"] for row in rows}) != 1:
            raise ValueError(f"{name} manifest mixes category or failure_k")
    if train_rows[0]["category"] != val_rows[0]["category"]:
        raise ValueError("train and val manifests must use the same category")
    if train_rows[0]["failure_k"] != val_rows[0]["failure_k"]:
        raise ValueError("train and val manifests must use the same failure_k")
    label_checkpoints = {str(resolve_artifact_path(value)) for value in
                         {row["label_checkpoint"] for row in train_rows + val_rows}}
    expected_checkpoint = str(resolve_artifact_path(point_checkpoint))
    if label_checkpoints != {expected_checkpoint}:
        raise ValueError("train and val labels must come from --point_checkpoint")


def make_loader(rows, args, processor, tokenizer, split):
    transform = get_transform(224, False)  # no stochastic augmentation in reliability calibration
    dataset = ReliabilityTrainingDataset(rows, args.data_root, processor, tokenizer, transform)
    generator = torch.Generator().manual_seed(args.seed)
    return DataLoader(
        dataset, batch_size=args.batch_size, shuffle=split == "train", num_workers=args.num_workers,
        collate_fn=collate, pin_memory=True, generator=generator,
    )


def class_weight(rows, device):
    positives = sum(row["failure_label"] for row in rows)
    negatives = len(rows) - positives
    if not positives or not negatives:
        raise ValueError("training manifest must contain both success and failure labels")
    return torch.tensor(negatives / positives, device=device, dtype=torch.float32)


def run_epoch(model, loader, retrieval_criterion, optimizer, device, args):
    training = optimizer is not None
    model.train(training)
    labels_all, probabilities_all = [], []
    totals = {"total_loss": 0.0, "retrieval_loss": 0.0, "failure_loss": 0.0}
    weight = class_weight(loader.dataset.rows, device) if training else None
    for batch in tqdm(loader, desc="train" if training else "val", mininterval=args.tqdm_mininterval):
        with torch.set_grad_enabled(training):
            outputs = model(
                batch["ref_images"].to(device), batch["text_input_ids"].to(device),
                batch["text_attention_mask"].to(device), batch["target_images"].to(device),
            )
            retrieval_loss = retrieval_criterion(
                mu_q=outputs["mu_q"], sigma_q=None, mu_c=outputs["mu_c"], sigma_c=None,
            )["total_loss"]
            labels = batch["failure_labels"].to(device)
            failure_loss = failure_prediction_loss(outputs["failure_logit"], labels, weight)
            # Point is frozen in v1: L_ret is an invariant monitor, while only
            # lambda*L_fail has a gradient. This avoids stale-label feedback.
            total_loss = retrieval_loss.detach() + args.lambda_failure * failure_loss
            if training:
                optimizer.zero_grad(); total_loss.backward()
                torch.nn.utils.clip_grad_norm_(model.reliability_head.parameters(), 1.0)
                optimizer.step()
        probabilities = torch.sigmoid(outputs["failure_logit"]).detach().cpu().tolist()
        labels_all.extend(int(value) for value in batch["failure_labels"].tolist())
        probabilities_all.extend(probabilities)
        totals["total_loss"] += float(total_loss.detach())
        totals["retrieval_loss"] += float(retrieval_loss.detach())
        totals["failure_loss"] += float(failure_loss.detach())
    metrics = reliability_metrics(labels_all, probabilities_all, args.ece_bins)
    metrics.update({key: value / len(loader) for key, value in totals.items()})
    return metrics


def atomic_save(payload, path):
    path = Path(path); path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    torch.save(payload, temporary); os.replace(temporary, path)


def main():
    args = parse_args(); set_seed(args.seed)
    if args.lambda_failure <= 0 or args.num_epochs <= 0 or args.patience < 0:
        raise ValueError("lambda_failure and num_epochs must be positive; patience must be non-negative")
    train_rows, val_rows = load_manifest(args.train_manifest), load_manifest(args.val_manifest)
    if args.max_train_rows: train_rows = train_rows[:args.max_train_rows]
    if args.max_val_rows: val_rows = val_rows[:args.max_val_rows]
    validate_manifests(train_rows, val_rows, args.point_checkpoint)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    processor, tokenizer = get_tokenizer_and_processor()
    train_loader = make_loader(train_rows, args, processor, tokenizer, "train")
    val_loader = make_loader(val_rows, args, processor, tokenizer, "val")
    model = ReliabilityAwareCIR.from_point_checkpoint(
        args.point_checkpoint, device, args.bottleneck_dim, args.dropout, freeze_backbone=True,
    ).to(device)
    retrieval_criterion = HUGLoss(recipe="point", uncertainty_is_variance=True).to(device)
    optimizer = torch.optim.AdamW(
        model.reliability_head.parameters(), lr=args.lr, weight_decay=args.weight_decay,
    )
    start_epoch, best_auroc, stale = 1, float("-inf"), 0
    if args.resume_checkpoint:
        resume = torch.load(args.resume_checkpoint, map_location=device)
        model.load_state_dict(resume["model_state_dict"], strict=True)
        optimizer.load_state_dict(resume["optimizer_state_dict"])
        start_epoch = resume["epoch"] + 1; best_auroc = resume.get("best_auroc", best_auroc)
        stale = resume.get("stale", 0)
    output = Path(args.output_dir); output.mkdir(parents=True, exist_ok=True)
    final_epoch, final_metrics = start_epoch - 1, {}
    saved_args = vars(args).copy(); saved_args["freeze_backbone"] = True
    for epoch in range(start_epoch, args.num_epochs + 1):
        train_metrics = run_epoch(model, train_loader, retrieval_criterion, optimizer, device, args)
        val_metrics = run_epoch(model, val_loader, retrieval_criterion, None, device, args)
        final_epoch, final_metrics = epoch, val_metrics
        print(json.dumps({"epoch": epoch, "train": train_metrics, "val": val_metrics}, allow_nan=False))
        score = val_metrics["auroc"] if val_metrics["auroc"] is not None else float("-inf")
        if score > best_auroc:
            best_auroc, stale = score, 0
            atomic_save(model.checkpoint_payload(saved_args, epoch, val_metrics), output / "checkpoint_best.pth")
        else:
            stale += 1
        last = model.checkpoint_payload(saved_args, epoch, val_metrics)
        last.update({"optimizer_state_dict": optimizer.state_dict(), "best_auroc": best_auroc, "stale": stale})
        atomic_save(last, output / "checkpoint_last.pth")
        if args.patience and stale >= args.patience:
            print(f"Early stopping at epoch {epoch}; best AUROC={best_auroc:.4f}")
            break
    atomic_save(model.checkpoint_payload(saved_args, final_epoch, final_metrics), output / "checkpoint_final.pth")
    print(f"Training completed; best validation AUROC={best_auroc:.4f}")


if __name__ == "__main__":
    main()
